name: Inspired
options:
  bundleIdPrefix: com.inspired-developers
  deploymentTarget:
    iOS: 18.0
  indentWidth: 4
  tabWidth: 4

configs:
  Debug (Local): debug
  Debug (Staging): debug
  Release (Staging): release
  Debug (Production): debug
  Release (Production): release

targets:
  Inspired:
    type: application
    platform: iOS
    sources: 
      - Inspired
      - path: Inspired/GoogleService-Info.plist
        optional: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.inspired-developers.Inspired
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_ASSET_PATHS: '"Inspired/Preview Content"'
      configs:
        Debug (Local):
          PRODUCT_BUNDLE_IDENTIFIER: com.inspired-developers.Inspired.staging
          OTHER_SWIFT_FLAGS: $(inherited) -DFIREBASE_EMULATOR
        Debug (Staging):
          PRODUCT_BUNDLE_IDENTIFIER: com.inspired-developers.Inspired.staging
        Release (Staging):
          PRODUCT_BUNDLE_IDENTIFIER: com.inspired-developers.Inspired.staging
    dependencies:
      - target: InspiredTests
      - target: InspiredUITests

  InspiredTests:
    type: bundle.unit-test
    platform: iOS
    sources: [InspiredTests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Inspired

  InspiredUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [InspiredUITests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Inspired

schemes:
  Inspired (Local):
    build:
      targets:
        Inspired: [run, test, profile, analyze, archive]
    run:
      config: Debug (Local)
    test:
      config: Debug (Local)
  
  Inspired (Staging):
    build:
      targets:
        Inspired: [run, test, profile, analyze, archive]
    run:
      config: Debug (Staging)
    test:
      config: Debug (Staging)

  Inspired (Production):
    build:
      targets:
        Inspired: [run, test, profile, analyze, archive]
    run:
      config: Debug (Production)
    test:
      config: Debug (Production)
