name: Inspired
options:
  bundleIdPrefix: com.inspired-developers
  deploymentTarget:
    iOS: 18.0
  indentWidth: 4
  tabWidth: 4

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 1.17.1
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 11.8.0
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: 1.17.0

configs:
  Debug (Local): debug
  Debug (Staging): debug
  Release (Staging): release
  Debug (Production): debug
  Release (Production): release

targets:
  Inspired:
    type: application
    platform: iOS
    sources: 
      - path: Inspired
      - path: Inspired/Resources/Localization
        name: Localization
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.inspired-developers.Inspired
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug (Local):
          PRODUCT_BUNDLE_IDENTIFIER: com.inspired-developers.Inspired.staging
          OTHER_SWIFT_FLAGS: $(inherited) -DFIREBASE_EMULATOR
        Debug (Staging):
          PRODUCT_BUNDLE_IDENTIFIER: com.inspired-developers.Inspired.staging
        Release (Staging):
          PRODUCT_BUNDLE_IDENTIFIER: com.inspired-developers.Inspired.staging
    dependencies:
      - package: ComposableArchitecture
      - package: ComposableArchitecture
        product: CasePaths
      - package: ComposableArchitecture
        product: CustomDump
      - package: ComposableArchitecture
        product: Dependencies
      - package: ComposableArchitecture
        product: DependenciesMacros
      - package: ComposableArchitecture
        product: IdentifiedCollections
      - package: ComposableArchitecture
        product: Perception
      - package: ComposableArchitecture
        product: PerceptionCore
      - package: ComposableArchitecture
        product: IssueReporting
      - package: ComposableArchitecture
        product: XCTestDynamicOverlay
      - package: ComposableArchitecture
        product: ConcurrencyExtras
      - package: ComposableArchitecture
        product: CombineSchedulers
      - package: ComposableArchitecture
        product: Clocks
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseMessaging

  InspiredTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - path: InspiredTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Inspired
      - package: SnapshotTesting
      - package: ComposableArchitecture
      - package: ComposableArchitecture
        product: CasePaths
      - package: ComposableArchitecture
        product: CustomDump
      - package: ComposableArchitecture
        product: Dependencies
      - package: ComposableArchitecture
        product: DependenciesMacros
      - package: ComposableArchitecture
        product: IdentifiedCollections
      - package: ComposableArchitecture
        product: Perception
      - package: ComposableArchitecture
        product: PerceptionCore
      - package: ComposableArchitecture
        product: IssueReporting
      - package: ComposableArchitecture
        product: XCTestDynamicOverlay
      - package: ComposableArchitecture
        product: ConcurrencyExtras
      - package: ComposableArchitecture
        product: CombineSchedulers
      - package: ComposableArchitecture
        product: Clocks

  InspiredUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [InspiredUITests]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Inspired

schemes:
  Inspired (Local):
    build:
      targets:
        Inspired: [run, test, profile, analyze, archive]
    run:
      config: Debug (Local)
      environmentVariables:
        IS_EMULATOR: "YES"
    test:
      config: Debug (Local)
      targets: [InspiredTests, InspiredUITests]
      environmentVariables:
        IS_EMULATOR: "YES"
        PROJECT_DIR: "$(PROJECT_DIR)"
  
  Inspired (Staging):
    build:
      targets:
        Inspired: [run, test, profile, analyze, archive]
    run:
      config: Debug (Staging)
    test:
      config: Debug (Staging)
      targets: [InspiredTests, InspiredUITests]

  Inspired (Production):
    build:
      targets:
        Inspired: [run, test, profile, analyze, archive]
    run:
      config: Debug (Production)
    test:
      config: Debug (Production)
      targets: [InspiredTests, InspiredUITests]
