# fastlane/Fastfile

default_platform(:ios)

platform :ios do
              desc "Run all unit and snapshot tests (Local Emulator)"
              lane :test do
                sh("cd ../../../.. && ./scripts/sync-strings.sh")
                sh("cd ../../../.. && ./scripts/generate-assets.sh")
                scan(
                  scheme: "Inspired (Local)",
              configuration: "Debug (Local)"
    )
  end

  desc "Deploy a new version to Firebase App Distribution (Staging)"
  lane :deploy_staging do
    sh("../../../scripts/fetch-config.sh staging")
    sh("xcodegen generate")

    build_app(
      scheme: "Inspired (Staging)",
      configuration: "Release (Staging)",
      export_method: "ad-hoc"
    )

    firebase_app_distribution(
      app: "1:99296584767:ios:some_app_id",
      groups: "staging-testers"
    )
  end

  desc "Deploy a new version to TestFlight (Production)"
  lane :deploy_prod do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true
    )

    sh("../../../scripts/fetch-config.sh prod")
    sh("xcodegen generate")

    build_app(
      scheme: "Inspired (Production)",
      configuration: "Release (Production)",
      export_method: "app-store"
    )

    upload_to_testflight(api_key: api_key)
  end
end
